[package]
name = "tari-wasmer-middlewares"
description = "Tari fork of wasmer-middlewares: metering with exposed global indexes for the Tari Ootle engine"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
readme = "README.md"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository = "https://github.com/tari-project/wasmer"
rust-version.workspace = true
version = "7.4.0"

[dependencies]
wasmer = { path = "../api", version = "=7.4.0", default-features = false, features = [
  "compiler",
  "wasmparser",
  "headless",
] }
wasmer-types = { path = "../types", version = "=7.4.0" }
wasmer-vm = { path = "../vm", version = "=7.4.0" }

[target.'cfg(not(target_os = "windows"))'.dev-dependencies]
wasmer = { path = "../api", version = "=7.4.0", default-features = false, features = [
  "compiler",
  "cranelift",
  "wat",
] }

[target.'cfg(target_os = "windows")'.dev-dependencies]
wasmer = { path = "../api", version = "=7.4.0", default-features = false, features = [
  "compiler",
  "v8",
  "wasmparser",
] }

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
features = ["wasmer/cranelift"]
